/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/archives/[year]/': RouteRecordInfo<'/archives/[year]/', '/archives/:year', { year: ParamValue<true> }, { year: ParamValue<false> }>,
    '/archives/[year]/[month]/': RouteRecordInfo<'/archives/[year]/[month]/', '/archives/:year/:month', { year: ParamValue<true>, month: ParamValue<true> }, { year: ParamValue<false>, month: ParamValue<false> }>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/categories/[...its]': RouteRecordInfo<'/categories/[...its]', '/categories/:its(.*)', { its: ParamValue<true> }, { its: ParamValue<false> }>,
    '/notes/': RouteRecordInfo<'/notes/', '/notes', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/crypto': RouteRecordInfo<'/posts/crypto', '/posts/crypto', Record<never, never>, Record<never, never>>,
    '/posts/draft': RouteRecordInfo<'/posts/draft', '/posts/draft', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/i18n': RouteRecordInfo<'/posts/i18n', '/posts/i18n', Record<never, never>, Record<never, never>>,
    '/posts/music/guitar/week-1': RouteRecordInfo<'/posts/music/guitar/week-1', '/posts/music/guitar/week-1', Record<never, never>, Record<never, never>>,
    '/posts/music/guitar/week-2': RouteRecordInfo<'/posts/music/guitar/week-2', '/posts/music/guitar/week-2', Record<never, never>, Record<never, never>>,
    '/posts/music/kpa/auxiliarry-in': RouteRecordInfo<'/posts/music/kpa/auxiliarry-in', '/posts/music/kpa/auxiliarry-in', Record<never, never>, Record<never, never>>,
    '/posts/music/kpa/external-effects': RouteRecordInfo<'/posts/music/kpa/external-effects', '/posts/music/kpa/external-effects', Record<never, never>, Record<never, never>>,
    '/posts/music/kpa/input': RouteRecordInfo<'/posts/music/kpa/input', '/posts/music/kpa/input', Record<never, never>, Record<never, never>>,
    '/posts/music/kpa/looper': RouteRecordInfo<'/posts/music/kpa/looper', '/posts/music/kpa/looper', Record<never, never>, Record<never, never>>,
    '/posts/music/kpa/mode-performance-baisc': RouteRecordInfo<'/posts/music/kpa/mode-performance-baisc', '/posts/music/kpa/mode-performance-baisc', Record<never, never>, Record<never, never>>,
    '/posts/music/kpa/mode-performance-edit': RouteRecordInfo<'/posts/music/kpa/mode-performance-edit', '/posts/music/kpa/mode-performance-edit', Record<never, never>, Record<never, never>>,
    '/posts/music/kpa/mode-performance-midi': RouteRecordInfo<'/posts/music/kpa/mode-performance-midi', '/posts/music/kpa/mode-performance-midi', Record<never, never>, Record<never, never>>,
    '/posts/music/kpa/noise-gate': RouteRecordInfo<'/posts/music/kpa/noise-gate', '/posts/music/kpa/noise-gate', Record<never, never>, Record<never, never>>,
    '/posts/music/kpa/output': RouteRecordInfo<'/posts/music/kpa/output', '/posts/music/kpa/output', Record<never, never>, Record<never, never>>,
    '/posts/music/kpa/parallel-path': RouteRecordInfo<'/posts/music/kpa/parallel-path', '/posts/music/kpa/parallel-path', Record<never, never>, Record<never, never>>,
    '/posts/music/kpa/peals-profiler': RouteRecordInfo<'/posts/music/kpa/peals-profiler', '/posts/music/kpa/peals-profiler', Record<never, never>, Record<never, never>>,
    '/posts/music/kpa/perimeter-controls': RouteRecordInfo<'/posts/music/kpa/perimeter-controls', '/posts/music/kpa/perimeter-controls', Record<never, never>, Record<never, never>>,
    '/posts/music/kpa/pure-cabinet': RouteRecordInfo<'/posts/music/kpa/pure-cabinet', '/posts/music/kpa/pure-cabinet', Record<never, never>, Record<never, never>>,
    '/posts/music/kpa/reamping': RouteRecordInfo<'/posts/music/kpa/reamping', '/posts/music/kpa/reamping', Record<never, never>, Record<never, never>>,
    '/posts/music/kpa/rig-manager': RouteRecordInfo<'/posts/music/kpa/rig-manager', '/posts/music/kpa/rig-manager', Record<never, never>, Record<never, never>>,
    '/posts/music/kpa/stack-amplifier': RouteRecordInfo<'/posts/music/kpa/stack-amplifier', '/posts/music/kpa/stack-amplifier', Record<never, never>, Record<never, never>>,
    '/posts/music/kpa/stack-eq': RouteRecordInfo<'/posts/music/kpa/stack-eq', '/posts/music/kpa/stack-eq', Record<never, never>, Record<never, never>>,
    '/posts/music/kpa/switches': RouteRecordInfo<'/posts/music/kpa/switches', '/posts/music/kpa/switches', Record<never, never>, Record<never, never>>,
    '/posts/music/kpa/volume-boost-pedal': RouteRecordInfo<'/posts/music/kpa/volume-boost-pedal', '/posts/music/kpa/volume-boost-pedal', Record<never, never>, Record<never, never>>,
    '/posts/music/song/悶々ふぁんもおらん': RouteRecordInfo<'/posts/music/song/悶々ふぁんもおらん', '/posts/music/song/悶々ふぁんもおらん', Record<never, never>, Record<never, never>>,
    '/posts/music/song/おくすり飲んで寝よう': RouteRecordInfo<'/posts/music/song/おくすり飲んで寝よう', '/posts/music/song/おくすり飲んで寝よう', Record<never, never>, Record<never, never>>,
    '/posts/music/song/サヨナラ深夜ちゃん': RouteRecordInfo<'/posts/music/song/サヨナラ深夜ちゃん', '/posts/music/song/サヨナラ深夜ちゃん', Record<never, never>, Record<never, never>>,
    '/posts/music/theory/1-basic': RouteRecordInfo<'/posts/music/theory/1-basic', '/posts/music/theory/1-basic', Record<never, never>, Record<never, never>>,
    '/posts/music/theory/2-temperament': RouteRecordInfo<'/posts/music/theory/2-temperament', '/posts/music/theory/2-temperament', Record<never, never>, Record<never, never>>,
    '/posts/music/theory/3-mode': RouteRecordInfo<'/posts/music/theory/3-mode', '/posts/music/theory/3-mode', Record<never, never>, Record<never, never>>,
    '/posts/music/theory/4-spectrum': RouteRecordInfo<'/posts/music/theory/4-spectrum', '/posts/music/theory/4-spectrum', Record<never, never>, Record<never, never>>,
    '/posts/music/theory/5-fingerboard': RouteRecordInfo<'/posts/music/theory/5-fingerboard', '/posts/music/theory/5-fingerboard', Record<never, never>, Record<never, never>>,
    '/posts/test': RouteRecordInfo<'/posts/test', '/posts/test', Record<never, never>, Record<never, never>>,
    '/posts/theme/': RouteRecordInfo<'/posts/theme/', '/posts/theme', Record<never, never>, Record<never, never>>,
    '/posts/theme/step-1': RouteRecordInfo<'/posts/theme/step-1', '/posts/theme/step-1', Record<never, never>, Record<never, never>>,
    '/posts/theme/step-2': RouteRecordInfo<'/posts/theme/step-2', '/posts/theme/step-2', Record<never, never>, Record<never, never>>,
    '/posts/theme/step-3': RouteRecordInfo<'/posts/theme/step-3', '/posts/theme/step-3', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
    '/tags/[tag]/': RouteRecordInfo<'/tags/[tag]/', '/tags/:tag', { tag: ParamValue<true> }, { tag: ParamValue<false> }>,
  }
}
